/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupsSubmitRouteImport } from './routes/startups.submit'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ResourcesSkillsIndexRouteImport } from './routes/resources.skills.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ResourcesSkillsSlugRouteImport } from './routes/resources.skills.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin/subscribers'
import { Route as AuthenticatedAdminStartupsRouteImport } from './routes/_authenticated/admin/startups'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminAuthorsRouteImport } from './routes/_authenticated/admin/authors'
import { Route as AuthenticatedAdminAgentRouteImport } from './routes/_authenticated/admin/agent'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated/admin/articles.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicSkillsFilesSplatRouteImport } from './routes/api/public/skills-files.$'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as ApiPublicHooksResubmitSitemapRouteImport } from './routes/api/public/hooks/resubmit-sitemap'
import { Route as ApiPublicHooksAgentRunRouteImport } from './routes/api/public/hooks/agent-run'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin/articles.$id'
import { Route as AuthenticatedAdminEmailPreviewStartupSubmissionIdRouteImport } from './routes/_authenticated/admin/email-preview.startup-submission.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsSubmitRoute = StartupsSubmitRouteImport.update({
  id: '/startups/submit',
  path: '/startups/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSkillsIndexRoute = ResourcesSkillsIndexRouteImport.update({
  id: '/resources/skills/',
  path: '/resources/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ResourcesSkillsSlugRoute = ResourcesSkillsSlugRouteImport.update({
  id: '/resources/skills/$slug',
  path: '/resources/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/admin/subscribers',
    path: '/admin/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStartupsRoute =
  AuthenticatedAdminStartupsRouteImport.update({
    id: '/admin/startups',
    path: '/admin/startups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuthorsRoute =
  AuthenticatedAdminAuthorsRouteImport.update({
    id: '/admin/authors',
    path: '/admin/authors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAgentRoute = AuthenticatedAdminAgentRouteImport.update({
  id: '/admin/agent',
  path: '/admin/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/admin/articles/',
    path: '/admin/articles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSkillsFilesSplatRoute =
  ApiPublicSkillsFilesSplatRouteImport.update({
    id: '/api/public/skills-files/$',
    path: '/api/public/skills-files/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksResubmitSitemapRoute =
  ApiPublicHooksResubmitSitemapRouteImport.update({
    id: '/api/public/hooks/resubmit-sitemap',
    path: '/api/public/hooks/resubmit-sitemap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentRunRoute = ApiPublicHooksAgentRunRouteImport.update({
  id: '/api/public/hooks/agent-run',
  path: '/api/public/hooks/agent-run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/admin/articles/$id',
    path: '/admin/articles/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute =
  AuthenticatedAdminEmailPreviewStartupSubmissionIdRouteImport.update({
    id: '/admin/email-preview/startup-submission/$id',
    path: '/admin/email-preview/startup-submission/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/startups/submit': typeof StartupsSubmitRoute
  '/admin/agent': typeof AuthenticatedAdminAgentRoute
  '/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/startups': typeof AuthenticatedAdminStartupsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/resources/skills/$slug': typeof ResourcesSkillsSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/resources/skills/': typeof ResourcesSkillsIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/api/public/hooks/agent-run': typeof ApiPublicHooksAgentRunRoute
  '/api/public/hooks/resubmit-sitemap': typeof ApiPublicHooksResubmitSitemapRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/skills-files/$': typeof ApiPublicSkillsFilesSplatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/email-preview/startup-submission/$id': typeof AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/startups/submit': typeof StartupsSubmitRoute
  '/admin/agent': typeof AuthenticatedAdminAgentRoute
  '/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/startups': typeof AuthenticatedAdminStartupsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/resources/skills/$slug': typeof ResourcesSkillsSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/resources/skills': typeof ResourcesSkillsIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/api/public/hooks/agent-run': typeof ApiPublicHooksAgentRunRoute
  '/api/public/hooks/resubmit-sitemap': typeof ApiPublicHooksResubmitSitemapRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/skills-files/$': typeof ApiPublicSkillsFilesSplatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/email-preview/startup-submission/$id': typeof AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/startups/submit': typeof StartupsSubmitRoute
  '/_authenticated/admin/agent': typeof AuthenticatedAdminAgentRoute
  '/_authenticated/admin/authors': typeof AuthenticatedAdminAuthorsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/startups': typeof AuthenticatedAdminStartupsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/resources/skills/$slug': typeof ResourcesSkillsSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/resources/skills/': typeof ResourcesSkillsIndexRoute
  '/_authenticated/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/api/public/hooks/agent-run': typeof ApiPublicHooksAgentRunRoute
  '/api/public/hooks/resubmit-sitemap': typeof ApiPublicHooksResubmitSitemapRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/skills-files/$': typeof ApiPublicSkillsFilesSplatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/_authenticated/admin/email-preview/startup-submission/$id': typeof AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/search'
    | '/setup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/article/$slug'
    | '/authors/$slug'
    | '/category/$slug'
    | '/email/unsubscribe'
    | '/startups/submit'
    | '/admin/agent'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/startups'
    | '/admin/subscribers'
    | '/admin/users'
    | '/lovable/email/suppression'
    | '/resources/skills/$slug'
    | '/admin/'
    | '/resources/skills/'
    | '/admin/articles/$id'
    | '/api/public/hooks/agent-run'
    | '/api/public/hooks/resubmit-sitemap'
    | '/api/public/media/$'
    | '/api/public/skills-files/$'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/articles/'
    | '/admin/email-preview/startup-submission/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/search'
    | '/setup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/article/$slug'
    | '/authors/$slug'
    | '/category/$slug'
    | '/email/unsubscribe'
    | '/startups/submit'
    | '/admin/agent'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/startups'
    | '/admin/subscribers'
    | '/admin/users'
    | '/lovable/email/suppression'
    | '/resources/skills/$slug'
    | '/admin'
    | '/resources/skills'
    | '/admin/articles/$id'
    | '/api/public/hooks/agent-run'
    | '/api/public/hooks/resubmit-sitemap'
    | '/api/public/media/$'
    | '/api/public/skills-files/$'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/articles'
    | '/admin/email-preview/startup-submission/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/search'
    | '/setup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/article/$slug'
    | '/authors/$slug'
    | '/category/$slug'
    | '/email/unsubscribe'
    | '/startups/submit'
    | '/_authenticated/admin/agent'
    | '/_authenticated/admin/authors'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/startups'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/users'
    | '/lovable/email/suppression'
    | '/resources/skills/$slug'
    | '/_authenticated/admin/'
    | '/resources/skills/'
    | '/_authenticated/admin/articles/$id'
    | '/api/public/hooks/agent-run'
    | '/api/public/hooks/resubmit-sitemap'
    | '/api/public/media/$'
    | '/api/public/skills-files/$'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/articles/'
    | '/_authenticated/admin/email-preview/startup-submission/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  StartupsSubmitRoute: typeof StartupsSubmitRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ResourcesSkillsSlugRoute: typeof ResourcesSkillsSlugRoute
  ResourcesSkillsIndexRoute: typeof ResourcesSkillsIndexRoute
  ApiPublicHooksAgentRunRoute: typeof ApiPublicHooksAgentRunRoute
  ApiPublicHooksResubmitSitemapRoute: typeof ApiPublicHooksResubmitSitemapRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicSkillsFilesSplatRoute: typeof ApiPublicSkillsFilesSplatRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/submit': {
      id: '/startups/submit'
      path: '/startups/submit'
      fullPath: '/startups/submit'
      preLoaderRoute: typeof StartupsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/skills/': {
      id: '/resources/skills/'
      path: '/resources/skills'
      fullPath: '/resources/skills/'
      preLoaderRoute: typeof ResourcesSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/resources/skills/$slug': {
      id: '/resources/skills/$slug'
      path: '/resources/skills/$slug'
      fullPath: '/resources/skills/$slug'
      preLoaderRoute: typeof ResourcesSkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/startups': {
      id: '/_authenticated/admin/startups'
      path: '/admin/startups'
      fullPath: '/admin/startups'
      preLoaderRoute: typeof AuthenticatedAdminStartupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/authors': {
      id: '/_authenticated/admin/authors'
      path: '/admin/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AuthenticatedAdminAuthorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agent': {
      id: '/_authenticated/admin/agent'
      path: '/admin/agent'
      fullPath: '/admin/agent'
      preLoaderRoute: typeof AuthenticatedAdminAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/skills-files/$': {
      id: '/api/public/skills-files/$'
      path: '/api/public/skills-files/$'
      fullPath: '/api/public/skills-files/$'
      preLoaderRoute: typeof ApiPublicSkillsFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resubmit-sitemap': {
      id: '/api/public/hooks/resubmit-sitemap'
      path: '/api/public/hooks/resubmit-sitemap'
      fullPath: '/api/public/hooks/resubmit-sitemap'
      preLoaderRoute: typeof ApiPublicHooksResubmitSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-run': {
      id: '/api/public/hooks/agent-run'
      path: '/api/public/hooks/agent-run'
      fullPath: '/api/public/hooks/agent-run'
      preLoaderRoute: typeof ApiPublicHooksAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/articles/$id': {
      id: '/_authenticated/admin/articles/$id'
      path: '/admin/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-preview/startup-submission/$id': {
      id: '/_authenticated/admin/email-preview/startup-submission/$id'
      path: '/admin/email-preview/startup-submission/$id'
      fullPath: '/admin/email-preview/startup-submission/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmailPreviewStartupSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAgentRoute: typeof AuthenticatedAdminAgentRoute
  AuthenticatedAdminAuthorsRoute: typeof AuthenticatedAdminAuthorsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStartupsRoute: typeof AuthenticatedAdminStartupsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
  AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute: typeof AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAgentRoute: AuthenticatedAdminAgentRoute,
  AuthenticatedAdminAuthorsRoute: AuthenticatedAdminAuthorsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStartupsRoute: AuthenticatedAdminStartupsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
  AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
  AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute:
    AuthenticatedAdminEmailPreviewStartupSubmissionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  StartupsSubmitRoute: StartupsSubmitRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ResourcesSkillsSlugRoute: ResourcesSkillsSlugRoute,
  ResourcesSkillsIndexRoute: ResourcesSkillsIndexRoute,
  ApiPublicHooksAgentRunRoute: ApiPublicHooksAgentRunRoute,
  ApiPublicHooksResubmitSitemapRoute: ApiPublicHooksResubmitSitemapRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicSkillsFilesSplatRoute: ApiPublicSkillsFilesSplatRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
